wandb_version: 1

wandb_entity:
  desc: null
  value: catemerfeld
wandb_project:
  desc: null
  value: ims_encoder_decoder
gpu:
  desc: null
  value: true
threads:
  desc: null
  value: 1
architecture:
  desc: null
  value: ims_to_onehot_encoder
optimizer:
  desc: null
  value: AdamW
loss:
  desc: null
  value: MSELoss
dataset:
  desc: null
  value: ims
target_embedding:
  desc: null
  value: OneHot
early stopping threshold:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 1.0e-06
_wandb:
  desc: null
  value:
    code_path: code/models/uninformative_embeddings/ims_to_onehot_encoder.py
    python_version: 3.10.16
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1739902100
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 16
      - 23
      4: 3.10.16
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
