wandb_version: 1

wandb_entity:
  desc: null
  value: catemerfeld
wandb_project:
  desc: null
  value: ims_encoder_decoder
gpu:
  desc: null
  value: true
threads:
  desc: null
  value: 1
architecture:
  desc: null
  value: carl_encoder
optimizer:
  desc: null
  value: AdamW
loss:
  desc: null
  value: MSELoss
dataset:
  desc: null
  value: carls
target_embedding:
  desc: null
  value: ChemNet
batch_size:
  desc: null
  value: 200
epochs:
  desc: null
  value: 500
learning_rate:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1738621843
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.0
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
